In [1]:
import numpy as _

In [2]:
a=[12,3,4,5]

In [3]:
q=_.array(a)

In [4]:
q

array([12,  3,  4,  5])

In [7]:
e=_.resize(q,[2,2])

In [8]:
e

array([[12,  3],
       [ 4,  5]])

In [9]:
r=[]
for i in range(9):
    r.append(i)

In [10]:
r

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [14]:
t=_.resize(a,[3,3])

In [15]:
t

array([[12,  3,  4],
       [ 5, 12,  3],
       [ 4,  5, 12]])

In [17]:
_.shape(t)

(3, 3)

In [21]:
import numpy as np

In [23]:
e=np.array([1,2,3],ndmin=5)

In [24]:
e

array([[[[[1, 2, 3]]]]])

In [28]:
a=np.arange(2,19,3)

In [29]:
a

array([ 2,  5,  8, 11, 14, 17])

In [30]:
type(a)

numpy.ndarray

In [5]:
import numpy as np
a=np.zeros([100,100])

In [6]:
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
t=[1,2,3,4]
a=np.asarray(t)

In [8]:
a

array([1, 2, 3, 4])

In [9]:
a=np.asarray(input("enter array:"))

enter array:1,2,3,4,5,6,7


In [7]:
np.ones([2,3,6],order="C")

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [8]:
np.ones_like([1,23])

array([1, 1])

In [10]:
a

array('1,2,3,4,5,6,7', dtype='<U13')

In [11]:
type(a)

numpy.ndarray

In [12]:
np.ones([2,3],order="C")

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.full([3,6],6)

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [17]:
w=np.array(2)

In [18]:
w

array(2)

In [19]:
np.shape(a)

()

In [20]:
np.size(a)

1

In [28]:
y=np.array(({1:2,2:3},{4:7,8:4}))

In [29]:
y

array([{1: 2, 2: 3}, {4: 7, 8: 4}], dtype=object)

In [30]:
np.size(y)

2

In [31]:
np.shape(y)

(2,)

In [32]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
import numpy as np
a=np.array([1,],ndmin=32)

In [4]:
a

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [5]:
q=np.arange(20).reshape(5,4)

In [35]:
q*4

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44],
       [48, 52, 56, 60],
       [64, 68, 72, 76]])

In [11]:
t=np.zeros_like([1,2,436,7,8,9]).reshape(3,2)

In [12]:
t

array([[0, 0],
       [0, 0],
       [0, 0]])

In [24]:
a=np.eye(4,4)

In [25]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
o=np.eye(4,5,k=-2)

In [29]:
o

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [30]:
a=np.random.rand(7)

In [31]:
a

array([0.25373473, 0.842349  , 0.54281034, 0.50257895, 0.56557598,
       0.47308766, 0.45567719])

In [36]:
a=[1,2]
b=[3,4]


In [37]:
q=np.array(a)

In [38]:
p=np.array(b)

In [39]:
p+q

array([4, 6])

In [40]:
p-q

array([2, 2])

In [41]:
p*q

array([3, 8])

In [42]:
p**2

array([ 9, 16], dtype=int32)

In [43]:
p/q

array([3., 2.])

In [44]:
p%q

array([0, 0], dtype=int32)

In [47]:
q.reshape(2,1)

array([[1],
       [2]])

In [48]:
p*q

array([3, 8])

In [49]:
q

array([1, 2])

In [50]:
p

array([3, 4])

In [54]:
w=q.reshape(1,2)

In [55]:
w

array([[1, 2]])

In [56]:
p*w

array([[3, 8]])

In [63]:
q=np.array([1,2,3,4])

In [57]:
b=np.array([2,3])

In [64]:
q

array([1, 2, 3, 4])

In [59]:
q+b

array([3, 5])

In [62]:
q

array([1, 2])

In [61]:
b

array([2, 3])

In [66]:
o=q.reshape(2,2)

In [67]:
o

array([[1, 2],
       [3, 4]])

In [68]:
b+o

array([[3, 5],
       [5, 7]])

In [1]:
import numpy as np

In [3]:
arr=np.array([4,7,2])

In [5]:
arr[1]

7

In [6]:
a=np.arange(1,200,6)

In [14]:
for i in a:
    print(a)

[  1   7  13  19  25  31  37  43  49  55  61  67  73  79  85  91  97 103
 109 115 121 127 133 139 145 151 157 163 169 175 181 187 193 199]
[  1   7  13  19  25  31  37  43  49  55  61  67  73  79  85  91  97 103
 109 115 121 127 133 139 145 151 157 163 169 175 181 187 193 199]
[  1   7  13  19  25  31  37  43  49  55  61  67  73  79  85  91  97 103
 109 115 121 127 133 139 145 151 157 163 169 175 181 187 193 199]
[  1   7  13  19  25  31  37  43  49  55  61  67  73  79  85  91  97 103
 109 115 121 127 133 139 145 151 157 163 169 175 181 187 193 199]
[  1   7  13  19  25  31  37  43  49  55  61  67  73  79  85  91  97 103
 109 115 121 127 133 139 145 151 157 163 169 175 181 187 193 199]
[  1   7  13  19  25  31  37  43  49  55  61  67  73  79  85  91  97 103
 109 115 121 127 133 139 145 151 157 163 169 175 181 187 193 199]
[  1   7  13  19  25  31  37  43  49  55  61  67  73  79  85  91  97 103
 109 115 121 127 133 139 145 151 157 163 169 175 181 187 193 199]
[  1   7  13  19  25  31  3

In [20]:
a=np.arange(1,490,7)
np.reshape(a,[35,2])

array([[  1,   8],
       [ 15,  22],
       [ 29,  36],
       [ 43,  50],
       [ 57,  64],
       [ 71,  78],
       [ 85,  92],
       [ 99, 106],
       [113, 120],
       [127, 134],
       [141, 148],
       [155, 162],
       [169, 176],
       [183, 190],
       [197, 204],
       [211, 218],
       [225, 232],
       [239, 246],
       [253, 260],
       [267, 274],
       [281, 288],
       [295, 302],
       [309, 316],
       [323, 330],
       [337, 344],
       [351, 358],
       [365, 372],
       [379, 386],
       [393, 400],
       [407, 414],
       [421, 428],
       [435, 442],
       [449, 456],
       [463, 470],
       [477, 484]])

In [42]:
a=np.arange(1,490,7)
r=np.reshape(a,[35,2])
for i in range(29):
    for j in range(2):
        print("elemnet found at",i,"and",j,"is",r[i][j])

elemnet found at 0 and 0 is 1
elemnet found at 0 and 1 is 8
elemnet found at 1 and 0 is 15
elemnet found at 1 and 1 is 22
elemnet found at 2 and 0 is 29
elemnet found at 2 and 1 is 36
elemnet found at 3 and 0 is 43
elemnet found at 3 and 1 is 50
elemnet found at 4 and 0 is 57
elemnet found at 4 and 1 is 64
elemnet found at 5 and 0 is 71
elemnet found at 5 and 1 is 78
elemnet found at 6 and 0 is 85
elemnet found at 6 and 1 is 92
elemnet found at 7 and 0 is 99
elemnet found at 7 and 1 is 106
elemnet found at 8 and 0 is 113
elemnet found at 8 and 1 is 120
elemnet found at 9 and 0 is 127
elemnet found at 9 and 1 is 134
elemnet found at 10 and 0 is 141
elemnet found at 10 and 1 is 148
elemnet found at 11 and 0 is 155
elemnet found at 11 and 1 is 162
elemnet found at 12 and 0 is 169
elemnet found at 12 and 1 is 176
elemnet found at 13 and 0 is 183
elemnet found at 13 and 1 is 190
elemnet found at 14 and 0 is 197
elemnet found at 14 and 1 is 204
elemnet found at 15 and 0 is 211
elemnet found 

In [40]:
r

array([[  1,   8],
       [ 15,  22],
       [ 29,  36],
       [ 43,  50],
       [ 57,  64],
       [ 71,  78],
       [ 85,  92],
       [ 99, 106],
       [113, 120],
       [127, 134],
       [141, 148],
       [155, 162],
       [169, 176],
       [183, 190],
       [197, 204],
       [211, 218],
       [225, 232],
       [239, 246],
       [253, 260],
       [267, 274],
       [281, 288],
       [295, 302],
       [309, 316],
       [323, 330],
       [337, 344],
       [351, 358],
       [365, 372],
       [379, 386],
       [393, 400],
       [407, 414],
       [421, 428],
       [435, 442],
       [449, 456],
       [463, 470],
       [477, 484]])

In [43]:
q=np.arange(1,900,3)

In [45]:
len(q)

300

In [47]:
w=np.reshape(q,[75,2,2])

In [48]:
w

array([[[  1,   4],
        [  7,  10]],

       [[ 13,  16],
        [ 19,  22]],

       [[ 25,  28],
        [ 31,  34]],

       [[ 37,  40],
        [ 43,  46]],

       [[ 49,  52],
        [ 55,  58]],

       [[ 61,  64],
        [ 67,  70]],

       [[ 73,  76],
        [ 79,  82]],

       [[ 85,  88],
        [ 91,  94]],

       [[ 97, 100],
        [103, 106]],

       [[109, 112],
        [115, 118]],

       [[121, 124],
        [127, 130]],

       [[133, 136],
        [139, 142]],

       [[145, 148],
        [151, 154]],

       [[157, 160],
        [163, 166]],

       [[169, 172],
        [175, 178]],

       [[181, 184],
        [187, 190]],

       [[193, 196],
        [199, 202]],

       [[205, 208],
        [211, 214]],

       [[217, 220],
        [223, 226]],

       [[229, 232],
        [235, 238]],

       [[241, 244],
        [247, 250]],

       [[253, 256],
        [259, 262]],

       [[265, 268],
        [271, 274]],

       [[277, 280],
        [283, 

In [52]:
for i in range(74):
    for j in range(2):
        for k in range(2):
            print("Element is found at",i,",",j,"and",k,"is",w[i][j][k])

Element is found at 0 , 0 and 0 is 1
Element is found at 0 , 0 and 1 is 4
Element is found at 0 , 1 and 0 is 7
Element is found at 0 , 1 and 1 is 10
Element is found at 1 , 0 and 0 is 13
Element is found at 1 , 0 and 1 is 16
Element is found at 1 , 1 and 0 is 19
Element is found at 1 , 1 and 1 is 22
Element is found at 2 , 0 and 0 is 25
Element is found at 2 , 0 and 1 is 28
Element is found at 2 , 1 and 0 is 31
Element is found at 2 , 1 and 1 is 34
Element is found at 3 , 0 and 0 is 37
Element is found at 3 , 0 and 1 is 40
Element is found at 3 , 1 and 0 is 43
Element is found at 3 , 1 and 1 is 46
Element is found at 4 , 0 and 0 is 49
Element is found at 4 , 0 and 1 is 52
Element is found at 4 , 1 and 0 is 55
Element is found at 4 , 1 and 1 is 58
Element is found at 5 , 0 and 0 is 61
Element is found at 5 , 0 and 1 is 64
Element is found at 5 , 1 and 0 is 67
Element is found at 5 , 1 and 1 is 70
Element is found at 6 , 0 and 0 is 73
Element is found at 6 , 0 and 1 is 76
Element is foun

In [28]:
a=np.arange(1,490,7)
for i in a:
    if (i%2==0):
        print("Elemnet is :",i)

Elemnet is : 8
Elemnet is : 22
Elemnet is : 36
Elemnet is : 50
Elemnet is : 64
Elemnet is : 78
Elemnet is : 92
Elemnet is : 106
Elemnet is : 120
Elemnet is : 134
Elemnet is : 148
Elemnet is : 162
Elemnet is : 176
Elemnet is : 190
Elemnet is : 204
Elemnet is : 218
Elemnet is : 232
Elemnet is : 246
Elemnet is : 260
Elemnet is : 274
Elemnet is : 288
Elemnet is : 302
Elemnet is : 316
Elemnet is : 330
Elemnet is : 344
Elemnet is : 358
Elemnet is : 372
Elemnet is : 386
Elemnet is : 400
Elemnet is : 414
Elemnet is : 428
Elemnet is : 442
Elemnet is : 456
Elemnet is : 470
Elemnet is : 484


In [58]:
a

array([  1,   8,  15,  22,  29,  36,  43,  50,  57,  64,  71,  78,  85,
        92,  99, 106, 113, 120, 127, 134, 141, 148, 155, 162, 169, 176,
       183, 190, 197, 204, 211, 218, 225, 232, 239, 246, 253, 260, 267,
       274, 281, 288, 295, 302, 309, 316, 323, 330, 337, 344, 351, 358,
       365, 372, 379, 386, 393, 400, 407, 414, 421, 428, 435, 442, 449,
       456, 463, 470, 477, 484])

In [2]:
import numpy as np
a=np.arange(1,200,6)


In [3]:
a

array([  1,   7,  13,  19,  25,  31,  37,  43,  49,  55,  61,  67,  73,
        79,  85,  91,  97, 103, 109, 115, 121, 127, 133, 139, 145, 151,
       157, 163, 169, 175, 181, 187, 193, 199])

In [4]:
a[a>100]

array([103, 109, 115, 121, 127, 133, 139, 145, 151, 157, 163, 169, 175,
       181, 187, 193, 199])

In [16]:
a=np.asarray()

In [17]:
a

array([1, 2, 3, 5])

array([], dtype=int32)

In [15]:
import numpy as np
a=np.arange(1,200,6)

In [16]:
a

array([  1,   7,  13,  19,  25,  31,  37,  43,  49,  55,  61,  67,  73,
        79,  85,  91,  97, 103, 109, 115, 121, 127, 133, 139, 145, 151,
       157, 163, 169, 175, 181, 187, 193, 199])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [23]:
a=np.arange(1,490,7)
r=np.reshape(a,[35,2])

In [24]:
r

array([[  1,   8],
       [ 15,  22],
       [ 29,  36],
       [ 43,  50],
       [ 57,  64],
       [ 71,  78],
       [ 85,  92],
       [ 99, 106],
       [113, 120],
       [127, 134],
       [141, 148],
       [155, 162],
       [169, 176],
       [183, 190],
       [197, 204],
       [211, 218],
       [225, 232],
       [239, 246],
       [253, 260],
       [267, 274],
       [281, 288],
       [295, 302],
       [309, 316],
       [323, 330],
       [337, 344],
       [351, 358],
       [365, 372],
       [379, 386],
       [393, 400],
       [407, 414],
       [421, 428],
       [435, 442],
       [449, 456],
       [463, 470],
       [477, 484]])

In [2]:
import numpy as np
a=np.arange(1,200,6)


In [3]:
a

array([  1,   7,  13,  19,  25,  31,  37,  43,  49,  55,  61,  67,  73,
        79,  85,  91,  97, 103, 109, 115, 121, 127, 133, 139, 145, 151,
       157, 163, 169, 175, 181, 187, 193, 199])

In [12]:
a[5:]

array([ 31,  37,  43,  49,  55,  61,  67,  73,  79,  85,  91,  97, 103,
       109, 115, 121, 127, 133, 139, 145, 151, 157, 163, 169, 175, 181,
       187, 193, 199])

In [13]:
a[4:13]

array([25, 31, 37, 43, 49, 55, 61, 67, 73])

In [14]:
a[4:30:8]

array([ 25,  73, 121, 169])

In [21]:
a=[1,2,3,4,5]

In [26]:
a1=np.array(a)
print(a1)

[1 2 3 4 5]


In [23]:
b=a1[1:4]

In [24]:
b[1]=10

In [25]:
print(a1)

[ 1  2 10  4  5]


In [29]:
a

array([  1,   8,  15,  22,  29,  36,  43,  50,  57,  64,  71,  78,  85,
        92,  99, 106, 113, 120, 127, 134, 141, 148, 155, 162, 169, 176,
       183, 190, 197, 204, 211, 218, 225, 232, 239, 246, 253, 260, 267,
       274, 281, 288, 295, 302, 309, 316, 323, 330, 337, 344, 351, 358,
       365, 372, 379, 386, 393, 400, 407, 414, 421, 428, 435, 442, 449,
       456, 463, 470, 477, 484])

In [30]:
a[-10]

421

In [31]:
q=np.transpose(a)

In [33]:
len(q)

70

In [37]:
q=np.reshape(a,[7,10])

In [38]:
q

array([[  1,   8,  15,  22,  29,  36,  43,  50,  57,  64],
       [ 71,  78,  85,  92,  99, 106, 113, 120, 127, 134],
       [141, 148, 155, 162, 169, 176, 183, 190, 197, 204],
       [211, 218, 225, 232, 239, 246, 253, 260, 267, 274],
       [281, 288, 295, 302, 309, 316, 323, 330, 337, 344],
       [351, 358, 365, 372, 379, 386, 393, 400, 407, 414],
       [421, 428, 435, 442, 449, 456, 463, 470, 477, 484]])

In [39]:
w=np.transpose(q)

In [40]:
w

array([[  1,  71, 141, 211, 281, 351, 421],
       [  8,  78, 148, 218, 288, 358, 428],
       [ 15,  85, 155, 225, 295, 365, 435],
       [ 22,  92, 162, 232, 302, 372, 442],
       [ 29,  99, 169, 239, 309, 379, 449],
       [ 36, 106, 176, 246, 316, 386, 456],
       [ 43, 113, 183, 253, 323, 393, 463],
       [ 50, 120, 190, 260, 330, 400, 470],
       [ 57, 127, 197, 267, 337, 407, 477],
       [ 64, 134, 204, 274, 344, 414, 484]])

In [41]:
y=w.transpose()

In [42]:
y

array([[  1,   8,  15,  22,  29,  36,  43,  50,  57,  64],
       [ 71,  78,  85,  92,  99, 106, 113, 120, 127, 134],
       [141, 148, 155, 162, 169, 176, 183, 190, 197, 204],
       [211, 218, 225, 232, 239, 246, 253, 260, 267, 274],
       [281, 288, 295, 302, 309, 316, 323, 330, 337, 344],
       [351, 358, 365, 372, 379, 386, 393, 400, 407, 414],
       [421, 428, 435, 442, 449, 456, 463, 470, 477, 484]])

In [44]:
y.shape


(7, 10)

In [45]:
a=[1,2,4,6]

In [50]:
import numpy as np
a=np.sin(np.array([1,2,3,35,45,56,7,6]))

In [51]:
a

array([ 0.84147098,  0.90929743,  0.14112001, -0.42818267,  0.85090352,
       -0.521551  ,  0.6569866 , -0.2794155 ])

In [52]:
base=2
height=6

In [53]:
np.hypot(base,height)

6.324555320336759

In [59]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.amin(a),np.amax(a))
print(np.percentile(a,20))

0.2713286716455455
0.39905330338932815
0.5760808500933092
0.3318691458442298
-0.5215510020869119 0.9092974268256817
-0.36867580097726094


In [1]:
import numpy as np

In [2]:
print(np.bitwise_and(even,odd))
odd=np.array([1,3,5,7,9,17,33])

print(np.bitwise_and(even,odd))

[ 0  2  4  6  8 16 32]


In [3]:
print(np.bitwise_or(even,odd))

[ 1  3  5  7  9 17 33]


In [4]:
print(np.bitwise_xor(even,odd))

[1 1 1 1 1 1 1]


In [3]:
import numpy as np
even=np.array([0,2,4,6,8,16,32])

In [5]:
print(np.invert(np.invert(even)))

[ 0  2  4  6  8 16 32]


In [6]:
a=np.array([1])

In [7]:
print(np.left_shift(a,3))

[8]


In [8]:
print(np.right_shift(a,3))

[0]


In [11]:
even=np.array([0.3,2.6,4.8,6.5,8.9,16.999,32.0])

In [12]:
np.ceil(even)

array([ 1.,  3.,  5.,  7.,  9., 17., 32.])

In [13]:
np.floor(even)

array([ 0.,  2.,  4.,  6.,  8., 16., 32.])

In [14]:
np.log2(even)

array([-1.73696559,  1.37851162,  2.26303441,  2.70043972,  3.15380534,
        4.08737797,  5.        ])

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mlt


In [2]:
a=[1,5,-2,5,6,8]

In [3]:
q=np.array(a)

In [4]:
q

array([ 1,  5, -2,  5,  6,  8])

In [5]:
w=np.sort(q)

In [6]:
w

array([-2,  1,  5,  5,  6,  8])

In [7]:
q

array([ 1,  5, -2,  5,  6,  8])

In [8]:
r=np.reshape(a,[3,2])

In [9]:
r

array([[ 1,  5],
       [-2,  5],
       [ 6,  8]])

In [10]:
np.sort(r,axis=0)

array([[-2,  5],
       [ 1,  5],
       [ 6,  8]])

In [11]:
np.sort(r,axis=-1)

array([[ 1,  5],
       [-2,  5],
       [ 6,  8]])

In [13]:
np.sort(r,axis=None)

array([-2,  1,  5,  5,  6,  8])

In [15]:
x=np.reshape(a,[1,2,3])

In [16]:
x

array([[[ 1,  5, -2],
        [ 5,  6,  8]]])

In [17]:
np.sort(x,axis=None)

array([-2,  1,  5,  5,  6,  8])

In [18]:
np.sort(x,axis=1)

array([[[ 1,  5, -2],
        [ 5,  6,  8]]])

In [19]:
np.sort(x,axis=0)

array([[[ 1,  5, -2],
        [ 5,  6,  8]]])

In [20]:
np.sort(x,axis=-1)

array([[[-2,  1,  5],
        [ 5,  6,  8]]])

In [21]:
a

[1, 5, -2, 5, 6, 8]

In [23]:
np.sort(a,kind="selectionsort")

array([-2,  1,  5,  5,  6,  8])

In [25]:
np.sort(a,kind="merge")

array([-2,  1,  5,  5,  6,  8])

In [26]:
np.sort(a,kind="heap")

array([-2,  1,  5,  5,  6,  8])

In [28]:
np.sort(a,kind="selection")

array([-2,  1,  5,  5,  6,  8])